server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_CONNECTION:jdbc:mysql://localhost:3306/church}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${U_MAIL}
    password: ${P_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


jwt:
  signerKey: ${S_K}


cloudinary:
  cloud_name: ${C_N}
  api_key: ${A_K}
  api_secret: ${A_S}

