server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_CONNECTION:jdbc:mysql://localhost:3306/church}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tringuyenquoc15102004@gmail.com
    password: nhej ckwm cglr zqyr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true






